import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "QuickDrive",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // Change to your favicon file
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative h-screen`}
        >
          <Header />
          <div className="h-[calc(100vh-10vh)]">{children}</div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
